<<<<<<< Updated upstream
baseURL = "https://alatae.com/"
=======
baseURL = "https://alatae.live/"
>>>>>>> Stashed changes
languageCode = "en-us"
title = "Ada Lovelace & the Analytical Engines"
theme = "archie"
copyright = "Â© Elijah Scheele"

[params]
    mode="dark"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/alatae"